baseURL = 'https://ejuravlev.github.io/'
languageCode = 'en-us'
title = 'Evgeniy Zhuravlev'
theme = 'ananke'

sectionPagesMenu = "main"

[pagination]
pagerSize = 3

[params]
text_color = ""
author = ""
favicon = "images/favicon.ico"
site_logo = ""
description = "DevOps notes"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3


[params.ananke.social.share]
networks = [
  "github",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "linkedin",
  "github"
]

[params.ananke.social.linkedin]
username = "evgeniy-zhuravlev-34942525b"

[params.ananke.social.github]
username = "ejuravlev"

